### ISSUE TITLE
pip3 install swampy is giving the python2 version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [AllenDowney/Swampy#5]
```
From Ubuntu 14.04:

1. sudo pip3 install swampy
2. python3
>>> import swampy.TurtleWorld

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/swampy/TurtleWorld.py", line 8, in <module>
    from Tkinter import TOP, BOTTOM, LEFT, RIGHT, END, LAST, NONE, SUNKEN
ImportError: No module named 'Tkinter'


Package python3-tk is installed, and the documentation at 
http://www.greenteapress.com/thinkpython/swampy/install.html while it doesn't 
mention pip3, hints that it should work with python3

Thank you!
```

Original issue reported on code.google.com by `YokoZar` on 20 Aug 2014 at 9:46

**Comment by TechOtter** [comment]
Ran into the same problem on OS X 10.11.6. Python3 installed with brew.

1. pip3 install swampy
2. python3
3. 
>>> from swampy.World import World
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/swampy/World.py", line 51
    print 'KeyboardInterrupt'
                            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by AllenDowney** [comment]
I have updated Swampy for Python 3.  Revised installation instructions are now at https://greenteapress.com/wp/swampy/
