### ISSUE TITLE
Lumpy import exception "No module named 'Gui'"

### ISSUE THREAD

**Issue by aaronchn** [AllenDowney/Swampy#7]
In order to use tkinter for python 3 with pyenv on Arch, I installed tk for arch and build python use pyenv again,and copy all files in your git repo(Swampy/tree/master/python3) to pyenv's sitepackges directory. Then, 'import tkinter' it works! 
But when 'from swampy.Lumpy import Lumpy' encountered the following exception.

```
Traceback (most recent call last):
  Python Shell, prompt 5, line 1
  File "/home/aaron/pyenv/versions/test_env_3.5.0/lib/python3.5/site-packages/swampy/Lumpy.py", line 36, in <module>
    from Gui import Gui, GuiCanvas, Point, BBox, underride, ScaleTransform
builtins.ImportError: No module named 'Gui'
```

**Comment by gocove** [comment]
They should be explicit relative imports now.
`from .Gui import Gui, GuiCanvas, Point, BBox, underride, ScaleTransform`

**Comment by AllenDowney** [comment]
I have updated Swampy for Python 3.  Revised installation instructions are now at https://greenteapress.com/wp/swampy/
